name: Test Clox

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test-clox:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Compile clox
      working-directory: clox
      run: gcc -o clox *.c

    - name: Run clox
      working-directory: clox
      run: ./clox
